---
apiVersion: batch/v1
kind: Job
metadata:
  # Unique key of the Job instance
  name: init-meta
  namespace: "{{ .Values.global.services_namespace }}"
spec:
  template:
    metadata:
      name: init-meta
    spec:
      initContainers:
      - name: init
        image: "{{ .Values.global.registry_url }}/service-checker:{{ .Values.global.kaapana_build_version  }}"
        imagePullPolicy:  {{ .Values.global.pull_policy_images }}
        env:
          - name: WAIT
            value: "os-dashboards,os-dashboards-service.{{  .Values.global.services_namespace  }}.svc,5601;opensearch,opensearch-service.{{  .Values.global.services_namespace  }}.svc,9200"
          - name: DELAY
            value: "1"
          - name: TIMEOUT
            value: "10"
      containers:
      - name: init-meta
        image: "{{ .Values.global.registry_url }}/init-meta:{{ .Values.global.kaapana_build_version  }}"
        imagePullPolicy:  {{ .Values.global.pull_policy_images }}
        env:
          - name: DOMAIN
            value: "{{ required "A valid hostname (or fqdn) is required!" .Values.global.hostname }}"
          - name: HTTPS_PORT
            value: "{{ .Values.global.https_port }}"
          - name: INIT_DASHBOARDS
            value: "True"
          - name: INIT_OPENSEARCH
            value: "True"
          - name: OS_HOST
            value: "opensearch-service.{{  .Values.global.services_namespace  }}.svc"
          - name: OS_PORT
            value: "9200"
          - name: INDEX
            value: "meta-index"
          - name: DASHBOARDS_URL
            value: "http://os-dashboards-service.{{  .Values.global.services_namespace  }}.svc:5601/meta"
          - name: EXPORT_NDJSON
            value: "/dashboards/export.ndjson"
        volumeMounts:
          - name: os-export-file
            mountPath: /dashboards/export.ndjson
            subPath: export.ndjson
      # Do not restart containers after they exit
      restartPolicy: Never
      volumes:
      - name: os-export-file
        configMap:
          name: os-export
          items:
          - key: export.ndjson
            path: export.ndjson
      imagePullSecrets:
      - name: registry-secret
  backoffLimit: 10